### ISSUE TITLE
enableLegacyDirtScreen not working

### ISSUE THREAD

**Issue by Xrey274** [SmushyTaco/Legacy-Display#8]
Running on 1.20.6, v1.1.9 and the legacyDirtScreen option, doesn't work. Menus are still transparent.

**Comment by SmushyTaco** [comment]
The vast majority of them aren't.

**Comment by Xrey274** [comment]
Huh? I don't understand?

**Comment by SmushyTaco** [comment]
Check out the latest 1.21.3 update :)
